Quality-jh/Models/Class.cs
namespace Quality_jh.Models
{
    public class Class
    {
    }
}

Quality-jh/Models/ErrorViewModel.cs
namespace Quality_jh.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Quality-jh/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Quality_jh.Models;
using System.Diagnostics;

namespace Quality_jh.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            

            ViewBag.NABHMandatoryTraning = new List<string>
            {
                "InfactionControlAndPrevantion", "QualityAndPatientSafety", "SafetyTrainings","BasicLifeSupport(BLS)","ACC"
            };

            ViewBag.SoftSkillOptions = new List<string>
            {
                "SST", 
            };
            return View();
        }

        //public IActionResult Privacy()
        //{
        //    return View();
        //}

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Quality-jh/Controllers/ManagefilesController.cs
using Grpc.Core;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using System.Threading.Tasks;
using System.Web;

namespace Quality_jh.Controllers
{
    public class ManagefilesController : Controller
    {
        public ActionResult MFile()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> MFile(IFormFile File)
        {
            if (ModelState.IsValid)
            {
                if (File != null && File.Length > 0)
                {
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/uploads", File.FileName);

                    //Using Buffering
                    using (var stream = System.IO.File.Create(filePath))
                    {
                        // The file is saved in a buffer before being processed
                        await File.CopyToAsync(stream);
                    }

                    //Using Streaming
                    //using (var stream = new FileStream(filePath, FileMode.Create, FileAccess.Write))
                    //{
                    //    await SingleFile.CopyToAsync(stream);
                    //}

                    // Process the file here (e.g., save to the database, storage, etc.)
                    return RedirectToAction("Retrieve");
                }
            }

            return View("Index");
        }

        public IActionResult Retrieve()
        {

            var dir = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/uploads");
            var files = Directory.EnumerateFiles(dir).Select(fn => Path.GetFileName(fn));
            //List<string> items = new List<string>();

            //foreach (var file in files)
            //{
            //    items.Add(file);
            //}

            return View(files);
        }

        public IActionResult Views() 
        {
            return View(files);
        }
        public IActionResult Download() 
        {
            return View(files);
        }
        public IActionResult Delete() 
        {
            return View(files);
        }
    }
}

    

Quality-jh/Controllers/NABHMandatoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace Quality_jh.Controllers
{
    public class NABHMandatoryTraning : Controller
    {
        
        public class InfectionControlController : Controller
        {
           public IActionResult InfectionControlAndPrevention()
           {

                return View();
           }
        }

        public IActionResult QualityAndPatientSafety()
        {
            return View();
        }

        public IActionResult SafetyTrainings()
        {
            return View();
        }

        public IActionResult BasicLifeSupportBLS()
        {
            return View();
        }
        public IActionResult ACC()
        {
            
            return View();
        }
    }
}

Quality-jh/Controllers/SoftSkillController.cs
using Microsoft.AspNetCore.Mvc;

namespace Quality_jh.Controllers
{
    public class SoftSkillTraning : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult SST()
        {
            return View();
        }
    }
}

Quality-jh/Views/Home/Index.cshtml
@* <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Jehangir Hospital Quality Control Dashboard</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" crossorigin="anonymous">
    <style>
        body {
            font-size: .875rem;
        }

        .sidebar {
            position: fixed;
            top: 0;
            bottom: 0;
            left: 0;
            z-index: 100; /* Behind the navbar */
            padding: 48px 0 0; /* Height of navbar */
        }

        .sidebar-sticky {
            position: -webkit-sticky;
            position: sticky;
            top: 0;
            height: calc(100vh - 48px);
            padding-top: .5rem;
            overflow-x: hidden;
            overflow-y: auto; /* Scrollable content */
        }

        .nav-link.active {
            color: #007bff;
        }

        .form-control {
            margin-bottom: 15px;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="#">JH Quality Control</a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </nav>

    <div class="container-fluid">
        <div class="row">
            <!-- Sidebar -->
            <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                <div class="sidebar-sticky pt-3">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" href="#">
                                <span data-feather="home"></span>
                                Dashboard
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="collapse" href="#nabhSubmenu" role="button" aria-expanded="false" aria-controls="nabhSubmenu">
                                NABH Mandated
                            </a>
                            <div class="collapse" id="nabhSubmenu">
                                <ul class="nav flex-column pl-3">
                                    <li class="nav-item">
                                        <a class="nav-link" href="#">Option 1</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="#">Option 2</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="#">Option 3</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="collapse" href="#nabhSubmenu" role="button" aria-expanded="false" aria-controls="nabhSubmenu">
                                Soft Skill Training
                            </a>
                            <div class="collapse" id="nabhSubmenu">
                                <ul class="nav flex-column pl-3">
                                    <li class="nav-item">
                                        <a class="nav-link" href="#">Option 1</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="#">Option 2</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="#">Option 3</a>
                                    </li>
                                </ul>
                            </div>

                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>

            <!-- Main content -->
            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                    <h1 class="h2">Jehangir Hospital Quality Control</h1>
                </div>

                <h2>JVRL Dashboard</h2>

             
            </main>
        </div>
    </div>

    <!-- Bootstrap JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
</body>
</html>
 *@
@{
    Layout = "_Layout";
}

Quality-jh/Views/Managefiles/MFile.cshtml
@using (Html.BeginForm("MFile", "Managefiles", FormMethod.Post,
   new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <fieldset>
        <legend>Upload a file</legend>
        <div class="editor-field">
            @Html.TextBox("file", "", new { type = "file" })
        </div>
        <div class="editor-field">
            <input type="submit" value="Upload" />
        </div>
    </fieldset>
}



@* @model List<string>

<h2>Downloads</h2>
<table>
    <tr>
        <th>File Name</th>
        <th>Link</th>
    </tr>
    @for (var i = 0; i <= Model.Count - 1; i++)
    {
        <tr>
            <td>
                @Model[i].ToString()
            </td>
            <td>
                @Html.ActionLink("Download", "Download", new { ImageName = @Model[i].ToString() })
            </td>
        </tr>
    }
</table> *@

Quality-jh/Views/Managefiles/Retrieve.cshtml
@model IEnumerable<string>

<h2>Retrieve</h2>
<table>
    <tr>
        <th>File Name</th>
        <th>Link</th>
        
        @* {action} *@
    </tr>
    @foreach (var file in Model)
    {
        <tr>
            <td>
                @file.ToString()
            </td>
            <td>
                @Html.ActionLink("Retrieve", "Retrieve", new { ImageName = @file.ToString() })
            </td>
        </tr>
    }
</table>

Quality-jh/Views/NABHMandatory/ACC.cshtml
<h1>ACC</h1>

Quality-jh/Views/NABHMandatory/InterFactionAndPrevantion.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1> InterFactionAndPrevantion</h1>

Quality-jh/Views/NABHMandatory/SafetyTrainings.cshtml
}

Quality-jh/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Jehangir Hospital Quality Control Document</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="#">Jehangir Hospital Quality Control Document</a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </nav>

    <div class="row">
        <!-- Sidebar -->
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
            <div class="sidebar-sticky pt-3">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link active" href="#">
                            <span data-feather="home"></span>
                            Quality Control
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-bs-toggle="collapse" href="#nabhSubmenu" role="button" aria-expanded="false" aria-controls="nabhSubmenu">
                            NABH Mandatory Traning
                        </a>
                        <div class="collapse" id="nabhSubmenu">
                            <ul class="nav flex-column pl-3">
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="NABHMandatoryTraning" asp-action="InFactionAndPrevantion">InfactionAndPrevention</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="NABHMandatoryTraning" asp-action="QualityAndPatientSafety">QualityAndPatientSafety </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="NABHMandatoryTraning" asp-action="SafetyTrainings">SafetyTrainings </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="NABHMandatoryTraning" asp-action="BasicLifeSupportBLS">BasicLifeSupportBLS </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="NABHMandatoryTraning" asp-action="ACC">ACC </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-bs-toggle="collapse" href="#skillsSubmenu" role="button" aria-expanded="false" aria-controls="skillsSubmenu">
                            Soft Skill Training
                        </a>
                        <div class="collapse" id="skillsSubmenu">
                            <ul class="nav flex-column pl-3">
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="SoftSkillTraining" asp-action="Comprehending Without Biases">Comprehending Without Biases</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="SoftSkillTraining" asp-action="Handling Difficult Patients & Resolving Bad Attitudes">Handling Difficult Patients & Resolving Bad Attitudes</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="SoftSkillTraining" asp-action="Negotiation Skills">Negotiation Skills</a>
                                </li>
                            </ul>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>

        <!-- Main content -->
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
               @*  <h1 class="h2">Jehangir Hospital Quality Control</h1> *@
            </div>

            <h3>Jehangir Virtual Learning Repository-(JVRL)</h3>
            @RenderBody()

        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Quality_jh - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <!-- Bootstrap 5 JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Quality-jh/Views/SoftSkillTraningcontroller/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Quality-jh/Views/SoftSkillTraningcontroller/SST.cshtml
<h1>SST</h1>